DataFrame হলো Pandas-এর সবচেয়ে গুরুত্বপূর্ণ structure। এটি rows ও columns সহ একটি 2-dimensional table। প্রতিটি column একটি Series। ML-এ dataset সবসময় DataFrame হিসেবে handle করা হয়।

pd.DataFrame()
pd.DataFrame(dict)
.shape
.columns
.dtypes
.info()
.head()
.tail()

In [1]:
import pandas as pd

In [2]:
data = {
  'Name':['Shaon','Mahi','Nahid','Kuasha'],
  'Age':[22,23,22,24],
  'Salary':[60000,40000,50000,55000]
}

In [3]:
df = pd.DataFrame(data)

df

     Name  Age  Salary
0   Shaon   22   60000
1    Mahi   23   40000
2   Nahid   22   50000
3  Kuasha   24   55000

In [4]:
df.shape

(4, 3)

In [5]:
df.columns.tolist()

['Name', 'Age', 'Salary']

In [6]:
df.index.tolist()

[0, 1, 2, 3]

In [7]:
df.dtypes

Name      object
Age        int64
Salary     int64
dtype: object

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [10]:
df.describe()

             Age        Salary
count   4.000000      4.000000
mean   22.750000  51250.000000
std     0.957427   8539.125638
min    22.000000  40000.000000
25%    22.000000  47500.000000
50%    22.500000  52500.000000
75%    23.250000  56250.000000
max    24.000000  60000.000000