In [3]:
def welcome_message():
  print('Welcome to Phitron Second Module')
  
welcome_message()

Welcome to Phitron Second Module

In [4]:
def welcome_message(name):
  print(f"Hello {name}!")
  
welcome_message("Shaon Khan")

Hello Shaon Khan!

In [5]:
def welcome_message(name="NoBody"):
  print(f"Hello {name}")

welcome_message("Shaon")
welcome_message()

Hello Shaon
Hello NoBody

In [15]:
def adder(a,b):
  """
  It actually helps to know what this function is about, this is acutally comment.
  """
  sum = a + b
  return sum

adder(20,30)

50

In [16]:
print(adder(20,30)*2)
help(adder)

100
Help on function adder in module __main__:

adder(a, b)
    It actually helps to know what this function is about, this is acutally comment.

In [17]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.

In [18]:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers

    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.

In [63]:
def sum_number(*args):
  print(args)
  print(sum(args))
  return args
  
  
sum_number(10,20,30,40) , type(sum_number(10,20,30,40))

(10, 20, 30, 40)
100
(10, 20, 30, 40)
100

((10, 20, 30, 40), tuple)

In [29]:
def add_args_number(*args):
  countSum = 0
  
  for lst in args:
    for i in lst:
      countSum += i
  
  print(countSum)
 
add_args_number([1,2,3,4,5],[10,20,30],[1],[1,2,5,6,8,1,1])

100

In [31]:
def dictionary(**kwargs):
  print(kwargs)
  
dictionary(a = 10, b = 20, c = 30, Shaon= 22)

{'a': 10, 'b': 20, 'c': 30, 'Shaon': 22}

In [32]:
def dictionary(**kwargs):
  for key,value in kwargs.items():
    print(f"{key}:{value}")
  
dictionary(a = 10, b = 20, c = 30, Shaon= 22)

a:10
b:20
c:30
Shaon:22

In [33]:
def returnFuc():
  print("Hello")
  
print(type(returnFuc()))

Hello
<class 'NoneType'>

In [34]:
def adder(a = 20,b = 30):
  print(a + b)
  
print(type(adder(10,20)))

30
<class 'NoneType'>

In [35]:
def adder(a = 20,b = 30):
  return (a + b)
  
print(type(adder(10,20)))

<class 'int'>

In [37]:
def adder(a,b):
  return a,b

print(adder(10,23),type(adder(10,23)))

#unzip

a , b = adder(2,3)

print(a,b)

(10, 23) <class 'tuple'>
2 3

In [41]:
s = {10,20,30,40,50,60,70,80,90,100}

s_iter = iter(s)

print(type(s_iter))
print(s_iter)
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))

<class 'set_iterator'>
<set_iterator object at 0x000002098E10AFC0>
100
70
40
10
80
50
20
90
60
30

In [39]:
s = [10,20,30,40,50,60,70,80,90,100]

s_iter = iter(s)

print(type(s_iter))
print(s_iter)

<class 'list_iterator'>
<list_iterator object at 0x000002098DB39FF0>

In [64]:
s = {
  'name':'Shaon',
  'age':22,
  'class':'Undergraduate'
}

s_iter = iter(s.items())
print(type(s_iter))
print(type(s))
print(s_iter)
print(next(s_iter))
print(next(s_iter))

<class 'dict_itemiterator'>
<class 'dict'>
<dict_itemiterator object at 0x000002098E08B5B0>
('name', 'Shaon')
('age', 22)

In [65]:
s = {
  'name':'Shaon',
  'age':22,
  'class':'Undergraduate'
}

s_iter = iter(s)
print(type(s_iter))
print(type(s))
print(s_iter)
print(next(s_iter))
print(next(s_iter))

<class 'dict_keyiterator'>
<class 'dict'>
<dict_keyiterator object at 0x00000209A658E5C0>
name
age

In [48]:
lst = [x**2 for x in range(500) ]

print(lst)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801, 10000, 10201, 10404, 10609, 10816, 11025, 11236, 11449, 11664, 11881, 12100, 12321, 12544, 12769, 12996, 13225, 13456, 13689, 13924, 14161, 14400, 14641, 14884, 15129, 15376, 15625, 15876, 16129, 16384, 16641, 16900, 17161, 17424, 17689, 17956, 18225, 18496, 18769, 19044, 19321, 19600, 19881, 20164, 20449, 20736, 21025, 21316, 21609, 21904, 22201, 22500, 22801, 23104, 23409, 23716, 24025, 24336, 24649, 24964, 25281, 25600, 25921, 26244, 26569, 26896, 27225, 27556, 27889, 28224, 28561, 28900, 29241, 29584, 29929, 30276, 30625, 30976, 31329, 31684, 32041, 32400, 32761, 33124, 33489, 33856, 34225, 34596, 34969, 35344, 35721, 36100, 36481, 36864, 37249, 37636, 38025, 38416, 38809, 39204, 39601, 40000, 40401, 40804, 41209, 41616, 42025, 42436, 42849, 43264, 43681, 44100, 44521, 44944, 45369, 45796, 46225, 46656, 47089, 47524, 47961, 48400, 48841, 49284, 49729, 50176, 50625, 51076, 51529, 51984, 52441, 52900, 53361, 53824, 54289, 54756, 55225, 55696, 56169, 56644, 57121, 57600, 58081, 58564, 59049, 59536, 60025, 60516, 61009, 61504, 62001, 62500, 63001, 63504, 64009, 64516, 65025, 65536, 66049, 66564, 67081, 67600, 68121, 68644, 69169, 69696, 70225, 70756, 71289, 71824, 72361, 72900, 73441, 73984, 74529, 75076, 75625, 76176, 76729, 77284, 77841, 78400, 78961, 79524, 80089, 80656, 81225, 81796, 82369, 82944, 83521, 84100, 84681, 85264, 85849, 86436, 87025, 87616, 88209, 88804, 89401, 90000, 90601, 91204, 91809, 92416, 93025, 93636, 94249, 94864, 95481, 96100, 96721, 97344, 97969, 98596, 99225, 99856, 100489, 101124, 101761, 102400, 103041, 103684, 104329, 104976, 105625, 106276, 106929, 107584, 108241, 108900, 109561, 110224, 110889, 111556, 112225, 112896, 113569, 114244, 114921, 115600, 116281, 116964, 117649, 118336, 119025, 119716, 120409, 121104, 121801, 122500, 123201, 123904, 124609, 125316, 126025, 126736, 127449, 128164, 128881, 129600, 130321, 131044, 131769, 132496, 133225, 133956, 134689, 135424, 136161, 136900, 137641, 138384, 139129, 139876, 140625, 141376, 142129, 142884, 143641, 144400, 145161, 145924, 146689, 147456, 148225, 148996, 149769, 150544, 151321, 152100, 152881, 153664, 154449, 155236, 156025, 156816, 157609, 158404, 159201, 160000, 160801, 161604, 162409, 163216, 164025, 164836, 165649, 166464, 167281, 168100, 168921, 169744, 170569, 171396, 172225, 173056, 173889, 174724, 175561, 176400, 177241, 178084, 178929, 179776, 180625, 181476, 182329, 183184, 184041, 184900, 185761, 186624, 187489, 188356, 189225, 190096, 190969, 191844, 192721, 193600, 194481, 195364, 196249, 197136, 198025, 198916, 199809, 200704, 201601, 202500, 203401, 204304, 205209, 206116, 207025, 207936, 208849, 209764, 210681, 211600, 212521, 213444, 214369, 215296, 216225, 217156, 218089, 219024, 219961, 220900, 221841, 222784, 223729, 224676, 225625, 226576, 227529, 228484, 229441, 230400, 231361, 232324, 233289, 234256, 235225, 236196, 237169, 238144, 239121, 240100, 241081, 242064, 243049, 244036, 245025, 246016, 247009, 248004, 249001]

In [51]:
def data_loader(chunkk_sizee,lst):
  for i in range(len(lst)):
    yield lst[i:i+chunkk_sizee]
    
    
x = data_loader(5,lst)
print(type(x))
print(next(x))
print(next(x))

<class 'generator'>
[0, 1, 4, 9, 16]
[1, 4, 9, 16, 25]

In [52]:
def data_loader(chunkk_sizee,lst):
  for i in range(0,len(lst),chunkk_sizee):
    yield lst[i:i+chunkk_sizee]
    
    
x = data_loader(5,lst)
print(type(x))
print(next(x))
print(next(x))

<class 'generator'>
[0, 1, 4, 9, 16]
[25, 36, 49, 64, 81]

In [55]:
import pandas as pd

df = pd.DataFrame({'Temperature (F)':[32,212,98.6,68]})

df['Temperature (C)'] = df['Temperature (F)'].apply(lambda x: (x - 32) * (5/9))

df

   Temperature (F)  Temperature (C)
0             32.0              0.0
1            212.0            100.0
2             98.6             37.0
3             68.0             20.0

In [56]:
df = pd.DataFrame({'A':[1,2,3,4,5,9],
                   'B': [5,6,7,8,9,99]})

df['A'] = df.A.map(lambda x: x ** 0.5)
df

          A   B
0  1.000000   5
1  1.414214   6
2  1.732051   7
3  2.000000   8
4  2.236068   9
5  3.000000  99

In [57]:
df = pd.DataFrame({'Total_Spent':[120,600,460,899,945,1020]})

df

   Total_Spent
0          120
1          600
2          460
3          899
4          945
5         1020

In [58]:
df['is_high_value'] = df['Total_Spent'].apply(lambda x: 1 if x > 500 else 0)

df

   Total_Spent  is_high_value
0          120              0
1          600              1
2          460              0
3          899              1
4          945              1
5         1020              1