In [2]:
import pandas as pd

df = pd.read_csv('student_performance_prediction.csv')

df.describe()

       Study Hours per Week  Attendance Rate  Previous Grades
count          38005.000000     38008.000000     38006.000000
mean               9.962744        75.276323        65.440107
std                5.031154        20.393418        16.503119
min              -12.300000       -14.300000         8.300000
25%                6.600000        61.600000        55.100000
50%               10.000000        75.300000        65.200000
75%               13.400000        88.800000        75.200000
max               32.400000       150.200000       200.000000

In [4]:
round(df['Previous Grades'].mean(),2)

np.float64(65.44)

In [5]:
df['Previous Grades'].max()

np.float64(200.0)

In [6]:
df['Previous Grades'].min()

np.float64(8.3)

In [7]:
df['Previous Grades'].count()

np.int64(38006)

In [8]:
df['Previous Grades'].median()

np.float64(65.2)

In [9]:
df['Previous Grades'].std()

np.float64(16.503118932089183)

In [10]:
df.head(4)

,Student ID,Study Hours per Week,Attendance Rate,Previous Grades,Participation in Extracurricular Activities,Parent Education Level,Passed
0,S00001,12.5,NaN,75.0,Yes,Master,Yes
1,S00002,9.3,95.3,60.6,No,High School,No
2,S00003,13.2,NaN,64.0,No,Associate,No
3,S00004,17.6,76.8,62.4,Yes,Bachelor,No

In [11]:
df['Parent Education Level'].value_counts()

Parent Education Level
Bachelor       7685
High School    7675
Doctorate      7610
Associate      7604
Master         7426
Name: count, dtype: int64

In [12]:
df['Parent Education Level'].value_counts(normalize = True).mul(100).round(2)

Parent Education Level
Bachelor       20.22
High School    20.20
Doctorate      20.03
Associate      20.01
Master         19.54
Name: proportion, dtype: float64

In [13]:
result = df.groupby("Parent Education Level")["Previous Grades"].mean().round(2)
print(result)

Parent Education Level
Associate      65.38
Bachelor       65.51
Doctorate      65.69
High School    64.96
Master         65.51
Name: Previous Grades, dtype: float64

In [14]:
result2 = df.groupby(
    "Participation in Extracurricular Activities"
)["Study Hours per Week"].mean().round(2)
print(result2)

Participation in Extracurricular Activities
No      9.92
Yes    10.00
Name: Study Hours per Week, dtype: float64

In [15]:
result3 = df.groupby("Passed")["Study Hours per Week"].mean().round(2)
print(result3)

Passed
No     10.01
Yes     9.91
Name: Study Hours per Week, dtype: float64

In [16]:
result4 = df.groupby("Passed")["Previous Grades"].mean().round(2)
print(result4)

Passed
No     65.39
Yes    65.51
Name: Previous Grades, dtype: float64

In [19]:
result = df.groupby("Passed")[
    ["Study Hours per Week", "Previous Grades", "Attendance Rate"]
].agg(["mean", "max", "min"]).round(2)

print(result)

       Study Hours per Week             Previous Grades              \
                       mean   max   min            mean    max  min
Passed
No                    10.01  32.4 -12.3           65.39  200.0  8.3
Yes                    9.91  29.6  -9.2           65.51  200.0  9.4

       Attendance Rate
                  mean    max   min
Passed
No               75.08  150.2 -14.3
Yes              75.46  150.0 -10.9

In [20]:
df_sorted = df.sort_values("Previous Grades", ascending=False)

In [21]:
df_sorted[[
    "Student ID",
    "Study Hours per Week",
    "Previous Grades",
    "Passed"
]].head(5)

      Student ID  Study Hours per Week  Previous Grades Passed
19101     S19102                   8.8            200.0     No
97        S00098                  11.3            200.0    Yes
32172     S32173                  -2.7            200.0    Yes
28459     S28460                  14.4            200.0    Yes
31284     S31285                   NaN            200.0    Yes

In [22]:
df_sorted[[
    "Student ID",
    "Study Hours per Week",
    "Previous Grades",
    "Passed"
]].tail(5)

      Student ID  Study Hours per Week  Previous Grades Passed
39923     S39924                  17.1              NaN     No
39932     S39933                  20.7              NaN    Yes
39961     S39962                  14.1              NaN     No
39964     S39965                   6.7              NaN     No
39998     S39999                  14.1              NaN     No

In [24]:
passed = df[df["Passed"] == "Yes"]

len(passed)

19011

In [25]:
passed

,Student ID,Study Hours per Week,Attendance Rate,Previous Grades,Participation in Extracurricular Activities,Parent Education Level,Passed
0,S00001,12.5,NaN,75.0,Yes,Master,Yes
5,S00006,8.8,73.8,69.3,Yes,High School,Yes
6,S00007,17.9,38.6,93.6,No,Doctorate,Yes
8,S00009,7.7,100.1,91.9,No,Bachelor,Yes
13,S00014,0.4,75.1,50.4,NaN,NaN,Yes
...,...,...,...,...,...,...,...
39986,S39987,18.2,108.1,75.5,No,NaN,Yes
39988,S39989,23.6,72.9,65.9,Yes,High School,Yes
39990,S39991,19.1,NaN,94.9,No,NaN,Yes
39996,S39997,11.3,66.4,64.2,No,Doctorate,Yes
39999,S40000,11.8,55.1,68.5,No,Bachelor,Yes

In [26]:
hardworking = df[df["Study Hours per Week"] >= 15]

hardworking

,Student ID,Study Hours per Week,Attendance Rate,Previous Grades,Participation in Extracurricular Activities,Parent Education Level,Passed
3,S00004,17.6,76.8,62.4,Yes,Bachelor,No
6,S00007,17.9,38.6,93.6,No,Doctorate,Yes
20,S00021,17.3,110.3,68.6,No,Bachelor,Yes
31,S00032,19.3,42.1,74.1,Yes,Associate,Yes
47,S00048,15.3,77.0,97.2,Yes,High School,Yes
...,...,...,...,...,...,...,...
39986,S39987,18.2,108.1,75.5,No,NaN,Yes
39988,S39989,23.6,72.9,65.9,Yes,High School,Yes
39990,S39991,19.1,NaN,94.9,No,NaN,Yes
39991,S39992,15.0,52.1,70.4,Yes,Master,No
39995,S39996,15.6,93.8,51.4,Yes,Master,No

In [27]:
hardworking[["Student ID", 
                    "Study Hours per Week", 
                    "Previous Grades", 
                    "Passed"]]

      Student ID  Study Hours per Week  Previous Grades Passed
3         S00004                  17.6             62.4     No
6         S00007                  17.9             93.6    Yes
20        S00021                  17.3             68.6    Yes
31        S00032                  19.3             74.1    Yes
47        S00048                  15.3             97.2    Yes
...          ...                   ...              ...    ...
39986     S39987                  18.2             75.5    Yes
39988     S39989                  23.6             65.9    Yes
39990     S39991                  19.1             94.9    Yes
39991     S39992                  15.0             70.4     No
39995     S39996                  15.6             51.4     No

[6115 rows x 4 columns]

In [28]:
top = df[(df["Previous Grades"] >= 80) & (df["Passed"] == "Yes")]
len(top)

2938