In [25]:
import pandas as pd


df = pd.read_csv('student_performance_prediction.csv')

df.head()

,Student ID,Study Hours per Week,Attendance Rate,Previous Grades,Participation in Extracurricular Activities,Parent Education Level,Passed
0,S00001,12.5,NaN,75.0,Yes,Master,Yes
1,S00002,9.3,95.3,60.6,No,High School,No
2,S00003,13.2,NaN,64.0,No,Associate,No
3,S00004,17.6,76.8,62.4,Yes,Bachelor,No
4,S00005,8.8,89.3,72.7,No,Master,No

In [26]:
df.isnull().sum()

Student ID                                        0
Study Hours per Week                           1995
Attendance Rate                                1992
Previous Grades                                1994
Participation in Extracurricular Activities    2000
Parent Education Level                         2000
Passed                                         2000
dtype: int64

In [27]:
df.shape

(40000, 7)

In [28]:
df = df.dropna()

In [29]:
df.shape

(29446, 7)

In [30]:
df.dropna(how='all', inplace=True)

df.shape

(29446, 7)

In [31]:
df.Passed.isnull().sum()

np.int64(0)

In [32]:
df.dropna(subset=['Passed'])
df.Passed.isnull().sum()

np.int64(0)

In [33]:
df.fillna(0)

,Student ID,Study Hours per Week,Attendance Rate,Previous Grades,Participation in Extracurricular Activities,Parent Education Level,Passed
1,S00002,9.3,95.3,60.6,No,High School,No
3,S00004,17.6,76.8,62.4,Yes,Bachelor,No
4,S00005,8.8,89.3,72.7,No,Master,No
5,S00006,8.8,73.8,69.3,Yes,High School,Yes
6,S00007,17.9,38.6,93.6,No,Doctorate,Yes
...,...,...,...,...,...,...,...
39994,S39995,5.1,92.1,46.1,Yes,Doctorate,No
39995,S39996,15.6,93.8,51.4,Yes,Master,No
39996,S39997,11.3,66.4,64.2,No,Doctorate,Yes
39997,S39998,13.1,65.6,38.1,No,Bachelor,No
39999,S40000,11.8,55.1,68.5,No,Bachelor,Yes

In [34]:
df.Passed.isnull().sum()

np.int64(0)

In [35]:
df.Passed.isnull().sum()

np.int64(0)