In [1]:
import pandas as pd

pd.__version__

'2.3.3'

In [2]:
df = pd.read_csv('student_performance_prediction.csv')

df.head()

,Student ID,Study Hours per Week,Attendance Rate,Previous Grades,Participation in Extracurricular Activities,Parent Education Level,Passed
0,S00001,12.5,NaN,75.0,Yes,Master,Yes
1,S00002,9.3,95.3,60.6,No,High School,No
2,S00003,13.2,NaN,64.0,No,Associate,No
3,S00004,17.6,76.8,62.4,Yes,Bachelor,No
4,S00005,8.8,89.3,72.7,No,Master,No

In [3]:
df.shape

(40000, 7)

In [4]:
df.columns.tolist()

['Student ID',
 'Study Hours per Week',
 'Attendance Rate',
 'Previous Grades',
 'Participation in Extracurricular Activities',
 'Parent Education Level',
 'Passed']

In [7]:
df.columns

Index(['Student ID', 'Study Hours per Week', 'Attendance Rate',
       'Previous Grades', 'Participation in Extracurricular Activities',
       'Parent Education Level', 'Passed'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 7 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Student ID                                   40000 non-null  object
 1   Study Hours per Week                         38005 non-null  float64
 2   Attendance Rate                              38008 non-null  float64
 3   Previous Grades                              38006 non-null  float64
 4   Participation in Extracurricular Activities  38000 non-null  object
 5   Parent Education Level                       38000 non-null  object
 6   Passed                                       38000 non-null  object
dtypes: float64(3), object(4)
memory usage: 2.1+ MB

In [9]:
df.head()

,Student ID,Study Hours per Week,Attendance Rate,Previous Grades,Participation in Extracurricular Activities,Parent Education Level,Passed
0,S00001,12.5,NaN,75.0,Yes,Master,Yes
1,S00002,9.3,95.3,60.6,No,High School,No
2,S00003,13.2,NaN,64.0,No,Associate,No
3,S00004,17.6,76.8,62.4,Yes,Bachelor,No
4,S00005,8.8,89.3,72.7,No,Master,No

In [17]:
df.tail(60)

,Student ID,Study Hours per Week,Attendance Rate,Previous Grades,Participation in Extracurricular Activities,Parent Education Level,Passed
39940,S39941,7.8,96.0,60.1,Yes,Master,No
39941,S39942,9.9,77.3,61.9,Yes,High School,No
39942,S39943,8.0,102.7,47.9,Yes,Doctorate,Yes
39943,S39944,9.9,72.4,50.8,No,Associate,No
39944,S39945,NaN,79.9,68.2,Yes,Master,No
39945,S39946,3.0,90.0,45.8,Yes,Bachelor,No
39946,S39947,13.2,79.0,64.1,Yes,Doctorate,Yes
39947,S39948,9.0,85.5,64.4,Yes,Master,No
39948,S39949,16.8,80.7,73.8,Yes,Bachelor,No
39949,S39950,NaN,46.7,79.4,Yes,Master,No
39950,S39951,8.0,90.3,72.5,No,Bachelor,No
39951,S39952,9.4,98.6,97.5,Yes,High School,Yes
39952,S39953,14.5,72.4,66.7,Yes,Master,Yes
39953,S39954,14.9,70.9,91.1,Yes,Associate,Yes
39954,S39955,NaN,80.9,28.9,Yes,High School,No
39955,S39956,14.4,113.9,70.3,Yes,Doctorate,Yes
39956,S39957,18.2,69.3,59.2,Yes,Associate,No
39957,S39958,11.3,87.4,70.2,Yes,Associate,Yes
39958,S39959,14.8,NaN,69.9,No,Doctorate,NaN
39959,S39960,16.4,87.0,77.5,No,Master,No
39960,S39961,11.1,49.5,76.0,Yes,Bachelor,No
39961,S39962,14.1,110.9,NaN,No,Master,No
39962,S39963,10.1,82.3,47.4,No,Master,Yes
39963,S39964,9.7,69.4,74.0,Yes,Bachelor,Yes
39964,S39965,6.7,70.0,NaN,Yes,Doctorate,No
39965,S39966,10.9,80.6,52.0,NaN,High School,Yes
39966,S39967,19.4,115.1,72.2,Yes,Doctorate,Yes
39967,S39968,5.5,105.9,67.8,No,Bachelor,Yes
39968,S39969,13.1,69.6,50.3,No,Associate,Yes
39969,S39970,11.6,76.9,45.4,Yes,Master,No
39970,S39971,17.4,77.9,66.8,Yes,Master,Yes
39971,S39972,18.3,NaN,61.8,No,High School,Yes
39972,S39973,5.4,70.4,56.8,No,Doctorate,Yes
39973,S39974,7.1,79.2,74.8,Yes,Master,Yes
39974,S39975,7.4,56.8,64.5,No,Doctorate,No
39975,S39976,7.6,109.5,80.3,No,Master,No
39976,S39977,8.0,52.5,73.9,NaN,Doctorate,No
39977,S39978,11.7,54.7,41.8,NaN,High School,Yes
39978,S39979,5.7,88.8,37.6,NaN,Doctorate,Yes
39979,S39980,6.4,80.6,77.4,No,Associate,No
39980,S39981,6.0,66.0,81.9,No,Bachelor,Yes
39981,S39982,12.5,95.1,73.9,Yes,Doctorate,No
39982,S39983,9.7,79.9,52.4,NaN,Associate,No
39983,S39984,8.8,112.0,86.6,No,Associate,No
39984,S39985,5.8,39.4,73.0,No,Bachelor,Yes
39985,S39986,2.0,64.6,80.4,No,Master,No
39986,S39987,18.2,108.1,75.5,No,NaN,Yes
39987,S39988,8.6,84.6,58.8,No,Doctorate,No
39988,S39989,23.6,72.9,65.9,Yes,High School,Yes
39989,S39990,13.9,66.9,62.0,No,Master,NaN
39990,S39991,19.1,NaN,94.9,No,NaN,Yes
39991,S39992,15.0,52.1,70.4,Yes,Master,No
39992,S39993,10.8,46.3,73.5,Yes,Doctorate,No
39993,S39994,7.0,86.3,65.5,No,Bachelor,No
39994,S39995,5.1,92.1,46.1,Yes,Doctorate,No
39995,S39996,15.6,93.8,51.4,Yes,Master,No
39996,S39997,11.3,66.4,64.2,No,Doctorate,Yes
39997,S39998,13.1,65.6,38.1,No,Bachelor,No
39998,S39999,14.1,74.9,NaN,Yes,Master,No
39999,S40000,11.8,55.1,68.5,No,Bachelor,Yes