In [1]:
import pandas as pd

scores = pd.Series([85, 90, 78, 92, 88])

scores

0    85
1    90
2    78
3    92
4    88
dtype: int64

In [2]:
print(scores)

0    85
1    90
2    78
3    92
4    88
dtype: int64

In [3]:
scores = pd.Series(
    [85, 90, 78, 92, 88],
    index = ['Shaon', 'Ayan', 'Nayem','Sadia','Shahadat']
)

scores

Shaon       85
Ayan        90
Nayem       78
Sadia       92
Shahadat    88
dtype: int64

In [7]:
scores = pd.Series(
    ['Shaon','Sadia','Ayan','Shahadat','Nayem'],
    index = ['ME','WIFE','BROTHER','BEST FRIEND','HE KNOWS']
)

scores

ME                Shaon
WIFE              Sadia
BROTHER            Ayan
BEST FRIEND    Shahadat
HE KNOWS          Nayem
dtype: object

In [8]:
scores['ME']

'Shaon'

In [9]:
scores['HE KNOWS']

'Nayem'

In [10]:
student_data = {
    'Math': 88,
    'English': 78,
    'Science': 89,
    'Bangla': 82,
    'ICT': 98
}

stu_sco = pd.Series(student_data)

stu_sco

Math       88
English    78
Science    89
Bangla     82
ICT        98
dtype: int64

In [15]:
stu_dataF = pd.DataFrame(student_data, index = [10])

stu_dataF

    Math  English  Science  Bangla  ICT
10    88       78       89      82   98

In [16]:
df = pd.read_csv('student_performance_prediction.csv')

df.head()

,Student ID,Study Hours per Week,Attendance Rate,Previous Grades,Participation in Extracurricular Activities,Parent Education Level,Passed
0,S00001,12.5,NaN,75.0,Yes,Master,Yes
1,S00002,9.3,95.3,60.6,No,High School,No
2,S00003,13.2,NaN,64.0,No,Associate,No
3,S00004,17.6,76.8,62.4,Yes,Bachelor,No
4,S00005,8.8,89.3,72.7,No,Master,No

In [17]:
exam_series = df['Passed']
type(exam_series)

pandas.core.series.Series

In [18]:
exam_series

0        Yes
1         No
2         No
3         No
4         No
        ...
39995     No
39996    Yes
39997     No
39998     No
39999    Yes
Name: Passed, Length: 40000, dtype: object

In [19]:
exam_series.head(10)

0    Yes
1     No
2     No
3     No
4     No
5    Yes
6    Yes
7     No
8    Yes
9    NaN
Name: Passed, dtype: object

In [20]:
exam_g = df['Previous Grades']

exam_g

0        75.0
1        60.6
2        64.0
3        62.4
4        72.7
         ...
39995    51.4
39996    64.2
39997    38.1
39998     NaN
39999    68.5
Name: Previous Grades, Length: 40000, dtype: float64

In [21]:
exam_g.max()

np.float64(200.0)

In [22]:
exam_g.min()

np.float64(8.3)

In [23]:
exam_g.mean()

np.float64(65.44010682523812)

In [24]:
exam_g.count()

np.int64(38006)

In [25]:
exam_g.nunique()

956

In [27]:
exam_g.value_counts().head(10)

Previous Grades
61.5    131
69.7    129
64.7    124
68.9    120
63.3    119
70.6    117
62.0    117
66.8    117
61.6    116
68.2    113
Name: count, dtype: int64

In [28]:
exam_hg = exam_g[exam_g > 90]
exam_hg.head()

6     93.6
8     91.9
16    98.0
21    98.2
43    94.1
Name: Previous Grades, dtype: float64

In [29]:
exam_hg.name

'Previous Grades'

In [30]:
exam_hg.dtype

dtype('float64')

In [31]:
exam_hg.size

1933

In [32]:
exam_hg.index

Index([    6,     8,    16,    21,    43,    47,    66,    97,    99,   153,
       ...
       39705, 39709, 39741, 39786, 39797, 39805, 39890, 39951, 39953, 39990],
      dtype='int64', length=1933)