In [1]:
import pandas as pd

df = pd.read_csv('student_performance_prediction.csv')
df.head(10)

,Student ID,Study Hours per Week,Attendance Rate,Previous Grades,Participation in Extracurricular Activities,Parent Education Level,Passed
0,S00001,12.5,NaN,75.0,Yes,Master,Yes
1,S00002,9.3,95.3,60.6,No,High School,No
2,S00003,13.2,NaN,64.0,No,Associate,No
3,S00004,17.6,76.8,62.4,Yes,Bachelor,No
4,S00005,8.8,89.3,72.7,No,Master,No
5,S00006,8.8,73.8,69.3,Yes,High School,Yes
6,S00007,17.9,38.6,93.6,No,Doctorate,Yes
7,S00008,13.8,95.8,59.2,Yes,Doctorate,No
8,S00009,7.7,100.1,91.9,No,Bachelor,Yes
9,S00010,12.7,38.4,37.8,Yes,High School,NaN

In [3]:
df = pd.read_csv('student_performance_prediction.csv', nrows = 100)
len(df)

100

In [4]:
df.shape

(100, 7)

In [7]:
df = pd.read_csv('student_performance_prediction.csv', usecols = ['Student ID',	'Study Hours per Week',	'Attendance Rate',	'Previous Grades'], nrows = 100)
df

   Student ID  Study Hours per Week  Attendance Rate  Previous Grades
0      S00001                  12.5              NaN             75.0
1      S00002                   9.3             95.3             60.6
2      S00003                  13.2              NaN             64.0
3      S00004                  17.6             76.8             62.4
4      S00005                   8.8             89.3             72.7
..        ...                   ...              ...              ...
95     S00096                   2.7             86.9              NaN
96     S00097                  11.5             77.3             54.8
97     S00098                  11.3             67.3            200.0
98     S00099                  10.0             54.8             49.1
99     S00100                   8.8             67.0             91.5

[100 rows x 4 columns]

In [8]:
df.shape

(100, 4)

In [10]:
for col in df.columns:
    print(f"{col:35} {df[col].dtype}")

Student ID                          object
Study Hours per Week                float64
Attendance Rate                     float64
Previous Grades                     float64

In [11]:
df.isnull().sum()

Student ID              0
Study Hours per Week    1
Attendance Rate         6
Previous Grades         3
dtype: int64

In [12]:
df.isnull().sum().sum()

np.int64(10)

In [14]:
df.isnull().any().any()

np.True_