In [2]:
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
import pandas as pd

df = pd.read_csv('data.csv') 
imputer = SimpleImputer(strategy='median')
df[['Age', 'Salary']] = imputer.fit_transform(df[['Age', 'Salary']])
X = df.drop('Target', axis=1)
y = df['Target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [3]:
df

,Age,Income,Salary,Rating,Annual_Income,Customer_Support_Calls,House_Price,Square_Feet,Temperature,City,Product_Type,Location,Diagnosis,Cabin,Embarked,Gender,Target,Price_Target
0,40.0,9165.0,55361.0,2.9,NaN,NaN,495310.0,2091,15.1,Dhaka,Unknown,A,NaN,NaN,S,Male,0,280.32
1,33.0,5522.0,48717.0,NaN,52868.0,1.0,368695.0,1504,28.3,Chittagong,C,C,Type3,NaN,S,Female,1,314.83
2,42.0,50589.0,64787.0,3.1,79526.0,2.0,453606.0,2052,22.0,Sylhet,A,C,Type1,NaN,C,Female,0,252.43
3,53.0,61289.0,80106.0,3.6,107581.0,1.0,359753.0,2075,22.7,Rajshahi,C,B,Type2,NaN,S,Female,0,239.21
4,32.0,1604.0,31872.0,4.0,89654.0,1.0,228869.0,1248,NaN,Rajshahi,A,C,Type2,NaN,S,Female,0,179.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,31.0,16472.0,50253.0,3.2,82289.0,4.0,NaN,1832,17.0,Dhaka,A,C,Type1,NaN,C,Female,0,309.92
996,56.0,11596.0,41951.0,2.7,32733.0,2.0,NaN,1127,17.0,Sylhet,A,C,Type1,Cabin_D,S,Male,0,222.41
997,42.0,NaN,44369.0,2.6,50537.0,2.0,346644.0,1654,24.7,Rajshahi,C,B,Type2,NaN,S,Female,0,221.89
998,34.5,276.0,52691.0,3.9,143880.0,4.0,307904.0,1908,Unknown,Rajshahi,B,B,NaN,NaN,Q,Female,0,293.69
999,41.0,384.0,54721.0,3.1,NaN,2.0,271184.0,1942,14.1,Dhaka,A,B,Type3,NaN,S,Male,0,246.77

In [4]:
missing_value = df.isnull().sum()
missing_value

Age                         0
Income                    150
Salary                      0
Rating                     80
Annual_Income             120
Customer_Support_Calls     80
House_Price               100
Square_Feet                 0
Temperature                50
City                       50
Product_Type                0
Location                    0
Diagnosis                 220
Cabin                     680
Embarked                    2
Gender                      0
Target                      0
Price_Target                0
dtype: int64

In [9]:
missing_percentage = df.isnull().sum() / len(df) * 100
missing_percentage

Age                        0.0
Income                    15.0
Salary                     0.0
Rating                     8.0
Annual_Income             12.0
Customer_Support_Calls     8.0
House_Price               10.0
Square_Feet                0.0
Temperature                5.0
City                       5.0
Product_Type               0.0
Location                   0.0
Diagnosis                 22.0
Cabin                     68.0
Embarked                   0.2
Gender                     0.0
Target                     0.0
Price_Target               0.0
dtype: float64

In [10]:
more_than_50 = missing_percentage[missing_percentage > 50]
more_than_50

Cabin    68.0
dtype: float64

In [11]:
print(more_than_50.index.tolist())

['Cabin']

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     1000 non-null   float64
 1   Income                  850 non-null    float64
 2   Salary                  1000 non-null   float64
 3   Rating                  920 non-null    float64
 4   Annual_Income           880 non-null    float64
 5   Customer_Support_Calls  920 non-null    float64
 6   House_Price             900 non-null    float64
 7   Square_Feet             1000 non-null   int64
 8   Temperature             950 non-null    object
 9   City                    950 non-null    object
 10  Product_Type            1000 non-null   object
 11  Location                1000 non-null   object
 12  Diagnosis               780 non-null    object
 13  Cabin                   320 non-null    object
 14  Embarked                998 non-null    object
 15  Gender                  1000 non-null   object
 16  Target                  1000 non-null   int64
 17  Price_Target            1000 non-null   float64
dtypes: float64(8), int64(2), object(8)
memory usage: 140.8+ KB

In [14]:
import numpy as np

In [15]:
df['Temperature'] = df['Temperature'].replace('Unknown',np.nan)
df['Temperature'] = pd.to_numeric(df['Temperature'])

In [16]:
imputer = SimpleImputer(strategy = 'mean')
df[['Temperature']] = imputer.fit_transform(df[['Temperature']])
df[['Temperature']]

     Temperature
0      15.100000
1      28.300000
2      22.000000
3      22.700000
4      22.469605
..           ...
995    17.000000
996    17.000000
997    24.700000
998    22.469605
999    14.100000

[1000 rows x 1 columns]