In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder,LabelEncoder,StandardScaler,MinMaxScaler

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer


from sklearn.linear_model import LogisticRegression

In [2]:
# Load the dataset from a CSV file into a pandas DataFrame
df = pd.read_csv("F:/Jupyter Projects/Phitron AL ML/Dataset/Titanic-Dataset.csv")

# Display 5 random rows to see what the data looks like
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
287,288,0,3,"Naidenoff, Mr. Penko",male,22.0,0,0,349206,7.8958,NaN,S
466,467,0,2,"Campbell, Mr. William",male,NaN,0,0,239853,0.0000,NaN,S
157,158,0,3,"Corn, Mr. Harry",male,30.0,0,0,SOTON/OQ 392090,8.0500,NaN,S
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
283,284,1,3,"Dorking, Mr. Edward Arthur",male,19.0,0,0,A/5. 10482,8.0500,NaN,S

In [3]:
df['Cabin'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 891 entries, 0 to 890
Series name: Cabin
Non-Null Count  Dtype
--------------  -----
204 non-null    object
dtypes: object(1)
memory usage: 7.1+ KB

In [4]:
df['Family_Size'] = df['SibSp'] + df['Parch'] + 1
df['Cabin'] = df['Cabin'].fillna("Missing")

df['Deck'] = df['Cabin'].astype(str).str[0]
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Size,Deck
836,837,0,3,"Pasic, Mr. Jakob",male,21.0,0,0,315097,8.6625,Missing,S,1,M
639,640,0,3,"Thorneycroft, Mr. Percival",male,NaN,1,0,376564,16.1000,Missing,S,2,M
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,Missing,S,3,M
743,744,0,3,"McNamee, Mr. Neal",male,24.0,1,0,376566,16.1000,Missing,S,2,M
290,291,1,1,"Barber, Miss. Ellen ""Nellie""",female,26.0,0,0,19877,78.8500,Missing,S,1,M

In [5]:
df['Deck'].value_counts()

Deck
M    687
C     59
B     47
D     33
E     32
A     15
F     13
G      4
T      1
Name: count, dtype: int64

In [6]:
# Separate the features (X) from the target we want to predict (y)
# We drop 'Survived' from X because that's our answer key
X = df.drop('Survived', axis=1)

# y contains only the survival status
y = df['Survived']

In [7]:
# Split data: 80% for training the model and 20% for testing its accuracy
# 'stratify=y' ensures both sets have a similar percentage of survivors
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [8]:
X_train

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Size,Deck
692,693,3,"Lam, Mr. Ali",male,NaN,0,0,1601,56.4958,Missing,S,1,M
481,482,2,"Frost, Mr. Anthony Wood ""Archie""",male,NaN,0,0,239854,0.0000,Missing,S,1,M
527,528,1,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S,1,C
855,856,3,"Aks, Mrs. Sam (Leah Rosen)",female,18.0,0,1,392091,9.3500,Missing,S,2,M
801,802,2,"Collyer, Mrs. Harvey (Charlotte Annie Tate)",female,31.0,1,1,C.A. 31921,26.2500,Missing,S,3,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...
359,360,3,"Mockler, Miss. Helen Mary ""Ellie""",female,NaN,0,0,330980,7.8792,Missing,Q,1,M
258,259,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,Missing,C,1,M
736,737,3,"Ford, Mrs. Edward (Margaret Ann Watson)",female,48.0,1,3,W./C. 6608,34.3750,Missing,S,5,M
462,463,1,"Gee, Mr. Arthur H",male,47.0,0,0,111320,38.5000,E63,S,1,E
507,508,1,"Bradley, Mr. George (""George Arthur Brayton"")",male,NaN,0,0,111427,26.5500,Missing,S,1,M

In [9]:
y_train

692    1
481    0
527    0
855    1
801    1
      ..
359    1
258    1
736    0
462    0
507    1
Name: Survived, Length: 712, dtype: int64

In [10]:
#age
mean_age = X_train['Age'].mean()
std_age = X_train['Age'].std()

X_train['Z_score'] = (X_train['Age'] - mean_age) / std_age

musk = (abs(X_train['Z_score']) <= 3)

X_train = X_train[musk]
y_train = y_train[musk]

# fare

fare_Q1 = X_train['Fare'].quantile(0.25)
fare_Q3 = X_train['Fare'].quantile(0.75)

IQR = fare_Q3 - fare_Q1

minimum = max(0 , fare_Q1 - 1.5 * IQR)
maximum = fare_Q3 + 1.5 * IQR

X_train['Fare'] = X_train['Fare'].clip(minimum, maximum)

C:\Users\HP\AppData\Local\Temp\ipykernel_17760\987313337.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['Fare'] = X_train['Fare'].clip(minimum, maximum)

In [11]:
# pipeline

# numerical
p1 = Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='mean')),
        ('scaler',StandardScaler())
    ]
)

p2 = Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='median')),
        ('scaler',MinMaxScaler())
    ]
)

In [18]:
# categories goes one after another via stricly following the order of the input
# categories = [[3, 2, 1]]

In [19]:
# pipeline

#  categorical columns

p3 = Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='most_frequent')),
        ('encoder',OneHotEncoder(sparse_output=False,drop='first',handle_unknown='ignore'))
    ]
)

p4 = Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='most_frequent')),
        # ('encoder',OrdinalEncoder(categories=categories)),
        ('scaler',MinMaxScaler())
    ]
)

In [20]:
preprocessor = ColumnTransformer(
    transformers=[
        ('pipeline_1',p1,['Age']),
        ('pipeline_2',p2,['Fare','Family_Size']),
        ('pipeline_3',p3,['Embarked','Sex','Deck']),
        ('pipeline_4',p4,['Pclass'])
    ],
    remainder='drop'
)
preprocessor

ColumnTransformer(transformers=[('pipeline_1',
                                 Pipeline(steps=[('imputer', SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['Age']),
                                ('pipeline_2',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', MinMaxScaler())]),
                                 ['Fare', 'Family_Size']),
                                ('pipeline_3',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 ['Embarked', 'Sex', 'Deck']),
                                ('pipeline_4',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('scaler', MinMaxScaler())]),
                                 ['Pclass'])])

In [21]:
le = LabelEncoder()

le.fit(y_train)

y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [22]:
lr_model = Pipeline(
    steps=[
        ('preprocessor',preprocessor),
        ('model',LogisticRegression(class_weight='balanced',max_iter=1000))
    ]
)
lr_model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('pipeline_1',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Age']),
                                                 ('pipeline_2',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   MinMaxScaler())]),
                                                  ['Fare', 'Family_Size']),
                                                 ('pipeline_3',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['Embarked', 'Sex', 'Deck']),
                                                 ('pipeline_4',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('scaler',
                                                                   MinMaxScaler())]),
                                                  ['Pclass'])])),
                ('model',
                 LogisticRegression(class_weight='balanced', max_iter=1000))])

In [23]:
lr_model.fit(X_train,y_train)

lr_model['model'].coef_
lr_model['model'].intercept_
lr_model['model'].classes_

array([0, 1], dtype=int64)

In [24]:
# Use the trained model to predict if passengers in the test set survived
y_pred = lr_model.predict(X_test)

# Get the raw probability scores (e.g., 0.85 chance of death, 0.15 chance of survival)
lr_model.predict_proba(X_test)

array([[0.85543017, 0.14456983],
       [0.92593465, 0.07406535],
       [0.7685645 , 0.2314355 ],
       [0.928108  , 0.071892  ],
       [0.37478972, 0.62521028],
       [0.44202027, 0.55797973],
       [0.25175168, 0.74824832],
       [0.59304741, 0.40695259],
       [0.48117882, 0.51882118],
       [0.78333317, 0.21666683],
       [0.86142739, 0.13857261],
       [0.81696302, 0.18303698],
       [0.33839858, 0.66160142],
       [0.70443222, 0.29556778],
       [0.14972022, 0.85027978],
       [0.8369456 , 0.1630544 ],
       [0.4656747 , 0.5343253 ],
       [0.86484996, 0.13515004],
       [0.79277267, 0.20722733],
       [0.23652632, 0.76347368],
       [0.86484996, 0.13515004],
       [0.19849595, 0.80150405],
       [0.86656272, 0.13343728],
       [0.46101982, 0.53898018],
       [0.86188201, 0.13811799],
       [0.02684696, 0.97315304],
       [0.67767805, 0.32232195],
       [0.63445361, 0.36554639],
       [0.81514811, 0.18485189],
       [0.81137069, 0.18862931],
       [0.88452103, 0.11547897],
       [0.01552534, 0.98447466],
       [0.84984772, 0.15015228],
       [0.64190515, 0.35809485],
       [0.77268049, 0.22731951],
       [0.74164356, 0.25835644],
       [0.7662544 , 0.2337456 ],
       [0.38997551, 0.61002449],
       [0.86142739, 0.13857261],
       [0.17488353, 0.82511647],
       [0.7925924 , 0.2074076 ],
       [0.01386476, 0.98613524],
       [0.8610936 , 0.1389064 ],
       [0.13543675, 0.86456325],
       [0.23268347, 0.76731653],
       [0.81765031, 0.18234969],
       [0.86351687, 0.13648313],
       [0.49854139, 0.50145861],
       [0.14573303, 0.85426697],
       [0.20373587, 0.79626413],
       [0.04712354, 0.95287646],
       [0.36300173, 0.63699827],
       [0.35654602, 0.64345398],
       [0.74401135, 0.25598865],
       [0.01786862, 0.98213138],
       [0.84629698, 0.15370302],
       [0.8736287 , 0.1263713 ],
       [0.28314327, 0.71685673],
       [0.28580074, 0.71419926],
       [0.59630642, 0.40369358],
       [0.30591837, 0.69408163],
       [0.28747692, 0.71252308],
       [0.78505386, 0.21494614],
       [0.83754104, 0.16245896],
       [0.42572472, 0.57427528],
       [0.30151442, 0.69848558],
       [0.05464937, 0.94535063],
       [0.87903635, 0.12096365],
       [0.59740057, 0.40259943],
       [0.69721552, 0.30278448],
       [0.10353742, 0.89646258],
       [0.81988973, 0.18011027],
       [0.42294414, 0.57705586],
       [0.0239348 , 0.9760652 ],
       [0.77049811, 0.22950189],
       [0.92651051, 0.07348949],
       [0.88866945, 0.11133055],
       [0.85900565, 0.14099435],
       [0.58881675, 0.41118325],
       [0.29565679, 0.70434321],
       [0.79448231, 0.20551769],
       [0.82205505, 0.17794495],
       [0.8679774 , 0.1320226 ],
       [0.84657697, 0.15342303],
       [0.27929235, 0.72070765],
       [0.3525195 , 0.6474805 ],
       [0.87968576, 0.12031424],
       [0.38104886, 0.61895114],
       [0.38018281, 0.61981719],
       [0.02196947, 0.97803053],
       [0.44591755, 0.55408245],
       [0.44688544, 0.55311456],
       [0.91846549, 0.08153451],
       [0.86499108, 0.13500892],
       [0.54513487, 0.45486513],
       [0.18119546, 0.81880454],
       [0.37941862, 0.62058138],
       [0.86142739, 0.13857261],
       [0.88866945, 0.11133055],
       [0.84911042, 0.15088958],
       [0.76640089, 0.23359911],
       [0.01890935, 0.98109065],
       [0.35626159, 0.64373841],
       [0.08806236, 0.91193764],
       [0.84646248, 0.15353752],
       [0.37221709, 0.62778291],
       [0.62797663, 0.37202337],
       [0.86499108, 0.13500892],
       [0.80505761, 0.19494239],
       [0.54925241, 0.45074759],
       [0.86142739, 0.13857261],
       [0.94145362, 0.05854638],
       [0.85183962, 0.14816038],
       [0.39420579, 0.60579421],
       [0.17998584, 0.82001416],
       [0.86142739, 0.13857261],
       [0.77218629, 0.22781371],
       [0.78314209, 0.21685791],
       [0.84561062, 0.15438938],
       [0.82426038, 0.17573962],
       [0.85687619, 0.14312381],
       [0.27317218, 0.72682782],
       [0.92045866, 0.07954134],
       [0.31990988, 0.68009012],
       [0.79868377, 0.20131623],
       [0.76301562, 0.23698438],
       [0.41410925, 0.58589075],
       [0.40296991, 0.59703009],
       [0.83807203, 0.16192797],
       [0.51757066, 0.48242934],
       [0.81407189, 0.18592811],
       [0.85697223, 0.14302777],
       [0.37478972, 0.62521028],
       [0.86225907, 0.13774093],
       [0.5667127 , 0.4332873 ],
       [0.80952206, 0.19047794],
       [0.0257764 , 0.9742236 ],
       [0.86142739, 0.13857261],
       [0.35632896, 0.64367104],
       [0.86479272, 0.13520728],
       [0.43532676, 0.56467324],
       [0.77938499, 0.22061501],
       [0.20793091, 0.79206909],
       [0.52219877, 0.47780123],
       [0.78151316, 0.21848684],
       [0.62638095, 0.37361905],
       [0.86499108, 0.13500892],
       [0.71378197, 0.28621803],
       [0.09863344, 0.90136656],
       [0.13094765, 0.86905235],
       [0.85264924, 0.14735076],
       [0.65830543, 0.34169457],
       [0.01815884, 0.98184116],
       [0.19161312, 0.80838688],
       [0.70439434, 0.29560566],
       [0.12696061, 0.87303939],
       [0.72269404, 0.27730596],
       [0.84922412, 0.15077588],
       [0.67379332, 0.32620668],
       [0.19853343, 0.80146657],
       [0.23850796, 0.76149204],
       [0.06861687, 0.93138313],
       [0.35632896, 0.64367104],
       [0.10639095, 0.89360905],
       [0.09001477, 0.90998523],
       [0.30970994, 0.69029006],
       [0.86893043, 0.13106957],
       [0.45106644, 0.54893356],
       [0.17016527, 0.82983473],
       [0.32827655, 0.67172345],
       [0.91382586, 0.08617414],
       [0.81988973, 0.18011027],
       [0.46359153, 0.53640847],
       [0.80152626, 0.19847374],
       [0.18172468, 0.81827532],
       [0.81150199, 0.18849801],
       [0.73472145, 0.26527855],
       [0.04550657, 0.95449343],
       [0.78579544, 0.21420456]])

In [25]:
from sklearn.metrics import accuracy_score,precision_score,recall_score

In [26]:
accuracy = accuracy_score(y_test,y_pred)
print(accuracy)
precision = precision_score(y_test,y_pred)
print(precision)
recall = recall_score(y_test,y_pred)
print(recall)

0.7653631284916201
0.6753246753246753
0.7536231884057971