In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import TargetEncoder

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import MaxAbsScaler

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LinearRegression, SGDRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegressionCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [23]:
df = pd.read_csv('data.csv')
df.head(3)

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN

[3 rows x 33 columns]

In [24]:
df.drop(columns=['id','Unnamed: 32'], inplace = True)
df.head(3)

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758

[3 rows x 31 columns]

In [25]:
df['diagnosis'] = df['diagnosis'].map({'M':1, 'B':0})
df.head(2)

   diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0          1        17.99  ...          0.4601                  0.11890
1          1        20.57  ...          0.2750                  0.08902

[2 rows x 31 columns]

In [26]:
df.sample(5)

     diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
173          0        11.08  ...          0.1902                  0.07313
15           1        14.54  ...          0.4218                  0.13410
305          0        11.60  ...          0.3244                  0.06745
145          0        11.90  ...          0.2727                  0.10360
42           1        19.07  ...          0.4670                  0.10380

[5 rows x 31 columns]

In [27]:
df.shape

(569, 31)

In [28]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['diagnosis']),df['diagnosis'],test_size=0.20, random_state=42, stratify=df['diagnosis'])

In [29]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((455, 30), (114, 30), (455,), (114,))

In [34]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), X_train.select_dtypes(include=np.number).columns)
    ]
)

pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier',SVC())
])

param_grid = {
    'classifier__C': [0.1, 0.5, 1, 5, 10],
    #'classifier__penalty': ['l1', 'l2'],
    'classifier__kernel': ['rbf', 'linear','poly', 'sigmoid'],
    #'classifier__epsilon': [0.1, 0.2, 0.5, 1, 2, 5, 10],
    'classifier__shrinking': [True, False]
}

grid_search = GridSearchCV(
    estimator = pipeline,
    param_grid = param_grid,
    scoring = 'accuracy',
    cv = 5,
    n_jobs = -1
)

In [ ]:
grid_search.fit(X_train, y_train)
grid_search.best_params_
grid_search.best_score_
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('num',
                                                                         StandardScaler(),
                                                                         Index(['radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean',
       'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'sm...
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object'))])),
                                       ('classifier', SVC())]),
             n_jobs=-1,
             param_grid={'classifier__C': [0.1, 0.5, 1, 5, 10],
                         'classifier__kernel': ['rbf', 'linear', 'poly',
                                                'sigmoid'],
                         'classifier__shrinking': [True, False]},
             scoring='accuracy')

In [36]:
grid_search.best_params_

{'classifier__C': 1,
 'classifier__kernel': 'rbf',
 'classifier__shrinking': True}

In [37]:
grid_search.best_score_

0.9736263736263737

In [38]:
best_model = grid_search.best_estimator_

In [39]:
best_model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean',
       'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object'))])),
                ('classifier', SVC(C=1))])

In [40]:
y_pred = best_model.predict(X_test)

In [41]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9736842105263158

In [42]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98        72
           1       1.00      0.93      0.96        42

    accuracy                           0.97       114
   macro avg       0.98      0.96      0.97       114
weighted avg       0.97      0.97      0.97       114

In [43]:
confusion_matrix(y_test, y_pred)

array([[72,  0],
       [ 3, 39]], dtype=int64)